FROM python:3.8.5-alpine
WORKDIR /api

#ENV FLASK_APP app.py
#ENV FLASK_RUN_HOST 0.0.0.0

COPY requirements.txt app.py ./

RUN pip install -r requirements.txt 
#COPY app.py ./

CMD [ "flask", "run" ]
